import { writeFileSync } from 'node:fs'
import {
  MAX_MIGRATION_SORT_ORDER,
  MAX_OVERFLOW_SORT_ORDER,
  sortOrderToPositionKey,
} from '../shared/position-key.ts'

function buildLookupSetup(minSortOrder: number, maxSortOrder: number): string {
  const rows: string[] = []
  for (let i = minSortOrder; i <= maxSortOrder; i++) {
    rows.push(`(${i}, '${sortOrderToPositionKey(i)}')`)
  }

  const chunkSize = 500
  const insertChunks: string[] = []
  for (let i = 0; i < rows.length; i += chunkSize) {
    const chunk = rows.slice(i, i + chunkSize)
    insertChunks.push(
      `INSERT INTO _position_key_lookup (sort_order, position_key) VALUES\n  ${chunk.join(',\n  ')};`,
    )
  }

  return `CREATE TABLE IF NOT EXISTS _position_key_lookup (
  sort_order INTEGER PRIMARY KEY,
  position_key TEXT NOT NULL
);

DELETE FROM _position_key_lookup;

${insertChunks.join('\n\n')}`
}

const lookupTeardown = `DROP TABLE IF EXISTS _position_key_lookup;`

const lookupSetup0009 = buildLookupSetup(0, MAX_MIGRATION_SORT_ORDER)
const lookupSetup0013 = buildLookupSetup(0, MAX_MIGRATION_SORT_ORDER)
const lookupSetup0014 = buildLookupSetup(MAX_MIGRATION_SORT_ORDER + 1, MAX_OVERFLOW_SORT_ORDER)

const migration0009 = `-- Regenerate position_key using valid fractional-indexing keys for sort_order 0..${MAX_MIGRATION_SORT_ORDER}.
-- Generated by scripts/generate-position-key-migration.mts — do not edit by hand.

${lookupSetup0009}

UPDATE notes
SET position_key = (
  SELECT position_key FROM _position_key_lookup WHERE sort_order = notes.sort_order
)
WHERE sort_order <= ${MAX_MIGRATION_SORT_ORDER};

${lookupTeardown}
`

const migration0013 = `-- Repair legacy position_key values produced as 'a' || sort_order (sort_order >= 10).
-- Does NOT touch valid dynamic fractional keys (e.g. a0V between a0 and a1).
-- Generated by scripts/generate-position-key-migration.mts — do not edit by hand.

${lookupSetup0013}

UPDATE notes
SET position_key = (
  SELECT position_key FROM _position_key_lookup WHERE sort_order = notes.sort_order
)
WHERE sort_order >= 10
  AND sort_order <= ${MAX_MIGRATION_SORT_ORDER}
  AND position_key = 'a' || sort_order;

${lookupTeardown}
`

const migration0014 = `-- Repair overflow legacy position_key values for sort_order ${MAX_MIGRATION_SORT_ORDER + 1}..${MAX_OVERFLOW_SORT_ORDER}.
-- Generated by scripts/generate-position-key-migration.mts — do not edit by hand.

${lookupSetup0014}

UPDATE notes
SET position_key = (
  SELECT position_key FROM _position_key_lookup WHERE sort_order = notes.sort_order
)
WHERE sort_order > ${MAX_MIGRATION_SORT_ORDER}
  AND sort_order <= ${MAX_OVERFLOW_SORT_ORDER}
  AND position_key = 'a' || sort_order;

${lookupTeardown}
`

writeFileSync('./migrations/0009_position_key_fractional.sql', migration0009)
writeFileSync('./migrations/0013_position_key_repair.sql', migration0013)
writeFileSync('./migrations/0014_position_key_overflow_repair.sql', migration0014)
console.log(
  `Wrote migrations/0009 (${MAX_MIGRATION_SORT_ORDER + 1} keys), 0013, and 0014 (${MAX_OVERFLOW_SORT_ORDER - MAX_MIGRATION_SORT_ORDER} overflow keys)`,
)
